### ISSUE TITLE
Chains missing estimated_upgrade_time when upgrade is found

### ISSUE THREAD

**Issue by joshlopes** [DefiantLabs/cosmos-upgrades#35]
![image](https://github.com/DefiantLabs/cosmos-upgrades/assets/3440849/2b165e84-2fda-4d83-9d94-7e194cea931f)

This chain has an upgrade but the upgrade time is `null` I guess that shouldn't happen.

**Comment by pharr117** [comment]
Thanks for the report, we have pushed a patch in #37 to retry the estimated upgrade time calculation if we fail to retrieve the data we need for this calculation.
