### ISSUE TITLE
persist chain registry data

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-upgrades#6]
Rework defiant infra to give a persistent disk that can be used to hold chain-registry data.  
Update the python code logic so If the data is less then X hours old, it should not need to be re-fetched.

**Comment by danbryan** [comment]
fyi @clemensgg  I dded a 1GB persistent storage available at /cr.  Still need to rework the code to choose where to save the cr data. I gave this a stab this morning, but was not working, ill try again later this weeknd, or if you want feel free.

**Comment by clemensgg** [comment]
oh yeah, we could do a `REPO_LOCATION` env var (defaults to ./ where it is currently extracted to).

it works great locally.
